### PR TITLE
remove (broken) wizards from UI

### PR DESCRIPTION
**Pull request by zehicle**
with changes to the wizards, these were not working.  removed from menus.

@Meshiest is pulling out the routes & methods in the controller.

### CODE REVIEW

**Comment by VictorLowther** [comment]
Can one of the admins verify this patch?

**Comment by galthaus** [comment]
Hemlock file?

**Comment by zehicle** [comment]
grrr... hold on

**Comment by zehicle** [comment]
amended the commit to fix gemlock.  wizards HATE hemlock

**Pull request merged**
