### PR TITLE
Create fast, non-secured path for testing if API is Alive (and provide EULA)

### PR DESCRIPTION
**Pull request by zehicle**
Looking at the log entries created by Consul health changes, it was clear that "rebar ping" was creating a lot of noise - especially if it was not given valid credentials.

I added a '/api/license?alive" to handle these requests outside of the login.  Without the ?alive flag, it returns the API EULA text (same as /doc/eula) which is already outside of the login domain.

Part of my objective was to make this very quiet logging and also low overhead.

Next step is to add rebar alive to the CLI.

### CODE REVIEW

**Comment by VictorLowther** [comment]
Can one of the admins verify this patch?

**Comment by galthaus** [comment]
So, that was the purpose of ping in the CLI.  It opens a client session to the endpoint with username and password.  The same code is done before all rebar cli calls as seen when doing a 'rebar nodes list', the same error messages are generated.  This is how the cli gets the challenge username and password from the digest auth headers.  The 401 returned has the username and password to use on the return trip.  Not sure what there is to fix or how to make this go away.

With regard to the ping command itself, I guess it could be changed, but the cli would need to be modified to change the default Pre API call in the CLI to not do the session call and instead do nothing for the ping replacement.  The ping replacement could then use the license/alive call and miss the message.  This will still spam the log with lots of logs because all requests are logged currently.

The rebar ping in the consul has the correct credentials, but it requires the 401 to move forward.  The browser login does the same thing, it just caches the results so the 401 message isn't generated all the time.

**Comment by galthaus** [comment]
With all that said, I can still take this if we want an unauthenticated request/reply path.

**Comment by galthaus** [comment]
I'll take this for the eula piece and the fact that alive (and the eula in general) is open is okay.

**Comment by ravolt** [comment]
Thanks.  That was my thinking.  This check if different than ping
because it checks the URL w/o credentials.  If you are troubleshooting,
that is helpful.

There's a need for it in the UX where you pick the URL target before
trying to login.

Adding the EULA is a nice add, so you can get EULA from the UX pre-login.

On 01/04/2016 02:37 PM, Greg Althaus wrote:
>
> I'll take this for the eula piece and the fact that alive (and the
> eula in general) is open is okay.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/digitalrebar/core/pull/1005#issuecomment-168799710>.
>

-- 

Rob
____________________________
Rob Hirschfeld, 512-773-7522

I am in CENTRAL (-6) time
http://robhirschfeld.com
twitter: @zehicle, github: zehicle & ravolt

**Comment by galthaus** [comment]
Okay, but I wouldn't change ping or the consul checks to use the EULA URL.  The UX usages make sense.

**Comment by ravolt** [comment]
I was thinking to add a "rebar alive" check.  use it where it makes sense.

On 01/04/2016 02:43 PM, Greg Althaus wrote:
>
> Okay, but I wouldn't change ping or the consul checks to use the EULA
> URL. The UX usages make sense.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/digitalrebar/core/pull/1005#issuecomment-168801359>.
>

-- 

Rob
____________________________
Rob Hirschfeld, 512-773-7522

I am in CENTRAL (-6) time
http://robhirschfeld.com
twitter: @zehicle, github: zehicle & ravolt

**Comment by galthaus** [comment]
Where does it make sense?

**Comment by ravolt** [comment]
If I'm trying to figure out why I cannot login and I want to eliminate
the credentials as part of the cause. 


On 01/04/2016 02:59 PM, Greg Althaus wrote:
>
> Where does it make sense?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/digitalrebar/core/pull/1005#issuecomment-168807154>.
>

-- 

Rob
____________________________
Rob Hirschfeld, 512-773-7522

I am in CENTRAL (-6) time
http://robhirschfeld.com
twitter: @zehicle, github: zehicle & ravolt

**Comment by galthaus** [comment]
Sorry, I get updating the rebar cli.  The question is where to use alive in the code? or more specifically, where to replace rebar ping with alive.   and right now I can see any.  I get the forensic use.  Though, it turns out ping doesn't validate the credentials returned in the 401 message.  it just returns worked regardless of the response content.  It just has to get a 401 from  the API.  :-|

**Comment by ravolt** [comment]
Hmmm, I should look at the ping.  When it calls /api/v2/digest then it
should get a 200 OK message back when the credentials are good.  I had
to add that for the UX.  It gets back the user info for the login.

Generally, all the digest mechanics are handled transparently.  When I
make a correct digest call from CURL, it just logs 200.  There is no 401.


On 01/04/2016 03:12 PM, Greg Althaus wrote:
>
> Sorry, I get updating the rebar cli. The question is where to use
> alive in the code? or more specifically, where to replace rebar ping
> with alive. and right now I can see any. I get the forensic use.
> Though, it turns out ping doesn't validate the credentials returned in
> the 401 message. it just returns worked regardless of the response
> content. It just has to get a 401 from the API. :-|
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/digitalrebar/core/pull/1005#issuecomment-168810235>.
>

-- 

Rob
____________________________
Rob Hirschfeld, 512-773-7522

I am in CENTRAL (-6) time
http://robhirschfeld.com
twitter: @zehicle, github: zehicle & ravolt

**Comment by galthaus** [comment]
Strange.  I get this 401 always.

```
rebar_api_1 | 2016-01-04 21:22:05.983 [31688] [INFO ] Started GET "/api/v2/nodes" for ::ffff:192.168.99.1 at 2016-01-04 21:22:05 +0000
rebar_api_1 | 2016-01-04 21:22:05.986 [31688] [INFO ] Processing by NodesController#index as JSON
rebar_api_1 | 2016-01-04 21:22:05.986 [31688] [INFO ] Parameters: {"api_version"=>"v2"}
rebar_api_1 | 2016-01-04 21:22:05.987 [31688] [INFO ] Filter chain halted as :rebar_auth rendered or redirected
rebar_api_1 | 2016-01-04 21:22:05.987 [31688] [INFO ] Completed 401 Unauthorized in 1ms (ActiveRecord: 0.0ms)
rebar_api_1 | 2016-01-04 21:22:05.990 [31688] [INFO ] Started GET "/api/v2/nodes" for ::ffff:192.168.99.1 at 2016-01-04 21:22:05 +0000
rebar_api_1 | 2016-01-04 21:22:05.991 [31688] [INFO ] Processing by NodesController#index as JSON
rebar_api_1 | 2016-01-04 21:22:05.991 [31688] [INFO ] Parameters: {"api_version"=>"v2"}
rebar_api_1 | 2016-01-04 21:22:05.992 [31688] [DEBUG] User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."username" = $1 LIMIT 1  [["username", "rebar"]]
rebar_api_1 | 2016-01-04 21:22:05.994 [31688] [DEBUG] Node Load (1.0ms)  SELECT "nodes".* FROM "nodes"
rebar_api_1 | 2016-01-04 21:22:06.112 [31688] [INFO ] Completed 200 OK in 9ms (Views: 5.4ms | ActiveRecord: 1.2ms)
```

with this command:
```
curl -k --digest -u rebar:rebar1 https://192.168.99.100:3000/api/v2/nodes
```

I can tell this is not a rebar ping test because it uses HEAD instead of GET or so it appears.

**Comment by zehicle** [comment]
rear API is re authenticating each call - we could consider storing the
session data in the environment.

On 01/04/2016 03:24 PM, Greg Althaus wrote:
>
> Strange. I get this 401 always.
>
> |rebar_api_1 | 2016-01-04 21:22:05.983 [31688] [INFO ] Started GET "/api/v2/nodes" for ::ffff:192.168.99.1 at 2016-01-04 21:22:05 +0000
> rebar_api_1 | 2016-01-04 21:22:05.986 [31688] [INFO ] Processing by NodesController#index as JSON
> rebar_api_1 | 2016-01-04 21:22:05.986 [31688] [INFO ] Parameters: {"api_version"=>"v2"}
> rebar_api_1 | 2016-01-04 21:22:05.987 [31688] [INFO ] Filter chain halted as :rebar_auth rendered or redirected
> rebar_api_1 | 2016-01-04 21:22:05.987 [31688] [INFO ] Completed 401 Unauthorized in 1ms (ActiveRecord: 0.0ms)
> rebar_api_1 | 2016-01-04 21:22:05.990 [31688] [INFO ] Started GET "/api/v2/nodes" for ::ffff:192.168.99.1 at 2016-01-04 21:22:05 +0000
> rebar_api_1 | 2016-01-04 21:22:05.991 [31688] [INFO ] Processing by NodesController#index as JSON
> rebar_api_1 | 2016-01-04 21:22:05.991 [31688] [INFO ] Parameters: {"api_version"=>"v2"}
> rebar_api_1 | 2016-01-04 21:22:05.992 [31688] [DEBUG] User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."username" = $1 LIMIT 1  [["username", "rebar"]]
> rebar_api_1 | 2016-01-04 21:22:05.994 [31688] [DEBUG] Node Load (1.0ms)  SELECT "nodes".* FROM "nodes"
> rebar_api_1 | 2016-01-04 21:22:06.112 [31688] [INFO ] Completed 200 OK in 9ms (Views: 5.4ms | ActiveRecord: 1.2ms)
> |
>
> with this command:
>
> |curl -k --digest -u rebar:rebar1 https://192.168.99.100:3000/api/v2/nodes
> |
>
> I can tell this is not a rebar ping test because it uses HEAD instead
> of GET or so it appears.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/digitalrebar/core/pull/1005#issuecomment-168813555>.
>

-- 
  

Rob
____________________________
Rob Hirschfeld, 512-773-7522
RackN CEO, Founder

I am in CENTRAL (-6) time
http://robhirschfeld.com
twitter: @zehicle, github: cloudedge & ravolt

**Comment by galthaus** [comment]
In my case, that won't help.  Each curl call is unique.  The browser and cli are storing it, I think, but I'd have to look closer.

**Pull request merged**
