### PR TITLE
DB Consolidate Migrations

### PR DESCRIPTION
**Pull request by zehicle**
As part of the Digital Rebar cleanups, I've merged all the migrations into a single migration.

This file has been tested to ensure that 1) it correctly migrates and 2) schema matches the original generated schema by comparing rake db:schema:dump outputs from old and new systems.

Some additional cleaning was found - there are NO more strings (all text).  Also, the doc table was eliminated.

### CODE REVIEW

**Comment by galthaus** [comment]
This fails because BDD still has a doc test that references code you removed.

**Comment by galthaus** [comment]
This is missing the actual database migration file changes!?!?!

**Comment by ravolt** [comment]
sigh - rebase messed up.

On 09/15/2015 10:04 AM, Greg Althaus wrote:
>
> This is missing the actual database migration file changes!?!?!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/digitalrebar/core/pull/797#issuecomment-140422409>.
>

-- 

Rob
____________________________
Rob Hirschfeld, 512-773-7522

I am in CENTRAL (-6) time
http://robhirschfeld.com
twitter: @zehicle, github: zehicle & ravolt

**Comment by zehicle** [comment]
The current failure is a BDD issue with the server runs API not returning a 404.  All other tests passed.

I'm investigating.

**Pull request merged**
